# Generated by Django 2.0.5 on 2018-09-23 11:44

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('Purchase Officer', 'Purchase Officer'), ('Principal Office', 'Principal Office'), ('Store Manager', 'Store Manager'), ('Lab-Incharge', 'Lab-Incharge'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20, null=True)),
                ('department', models.CharField(blank=True, choices=[('MCA', 'MCA'), ('IT', 'IT'), ('CE', 'CE'), ('EXTC', 'EXTC'), ('INSTRUMENT', 'INSTRUMENT')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
