# Generated by Django 2.0.5 on 2018-09-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('MCA', 'MCA'), ('IT', 'IT'), ('CE', 'CE'), ('EXTC', 'EXTC'), ('INSTRUMENT', 'INSTRUMENT')], max_length=20, null=True),
        ),
    ]
