# Generated by Django 2.0.5 on 2018-09-23 22:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('quantity_required', models.IntegerField()),
                ('expected_date', models.DateField()),
                ('status', models.CharField(default='requested', max_length=30)),
                ('role', models.CharField(max_length=40)),
                ('last_updated_by_role', models.CharField(default='self', max_length=30)),
                ('requesting_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('last_update', models.DateField(auto_now=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
